# backtesting/backtest_report.py
"""
Backtest performance reporter.

Reads from backtest_trades + backtest_summary, computes full metrics,
formats Telegram summary, exports optimal_parameters.json, and writes
additional SQLite tables (monthly_performance, feature_importance rankings).

Usage:
    reporter = BacktestReporter()
    await reporter.start()
    report = await reporter.generate()
    print(report.telegram_summary)
    await reporter.stop()
"""

from __future__ import annotations

import json
import math
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import aiosqlite
import numpy as np
from loguru import logger

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

BACKTEST_DB_PATH = Path(__file__).parent.parent / "data" / "backtest.db"
MODELS_DIR       = Path(__file__).parent.parent / "models"
OPT_PARAMS_PATH  = MODELS_DIR / "optimal_parameters.json"
MODELS_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class ExitBreakdown:
    take_profit_2x:  int = 0
    take_profit_5x:  int = 0
    take_profit_10x: int = 0
    trailing_stop:   int = 0
    emergency_stop:  int = 0
    time_stop:       int = 0
    other:           int = 0

    @property
    def total(self) -> int:
        return (
            self.take_profit_2x + self.take_profit_5x + self.take_profit_10x
            + self.trailing_stop + self.emergency_stop + self.time_stop + self.other
        )


@dataclass
class MonthlyRow:
    year_month: str
    trades: int
    wins: int
    pnl_sol: float
    win_rate: float


@dataclass
class ScoreThresholdRow:
    threshold: float
    trades: int
    wins: int
    win_rate: float
    avg_pnl_sol: float
    profit_factor: float


@dataclass
class BacktestReport:
    # Token universe
    tokens_analyzed:     int = 0
    tokens_signalled:    int = 0

    # Trade statistics
    total_trades:        int   = 0
    wins:                int   = 0
    losses:              int   = 0
    win_rate:            float = 0.0
    avg_win_pct:         float = 0.0
    avg_loss_pct:        float = 0.0
    profit_factor:       float = 0.0
    sharpe_ratio:        float = 0.0
    max_drawdown_pct:    float = 0.0

    # Capital
    starting_sol:        float = 1.0
    ending_sol:          float = 1.0
    total_pnl_sol:       float = 0.0
    total_pnl_pct:       float = 0.0
    fees_paid_sol:       float = 0.0

    # Signal threshold
    optimal_score:       float = 0.72
    optimal_pos_size:    float = 0.05
    optimal_stop_loss:   float = 0.30

    # Rug analysis
    rugs_encountered:    int   = 0
    rugs_caught_pct:     float = 0.0
    avg_rug_loss_pct:    float = 0.0

    # Top feature
    top_feature:         str   = ""
    rug_detection_acc:   float = 0.0

    # Best / worst month
    best_month:          str   = ""
    best_month_pnl:      float = 0.0
    worst_month:         str   = ""
    worst_month_pnl:     float = 0.0

    # Breakdowns (not in telegram summary — stored separately)
    exit_breakdown:      ExitBreakdown = field(default_factory=ExitBreakdown)
    monthly_rows:        List[MonthlyRow] = field(default_factory=list)
    score_thresholds:    List[ScoreThresholdRow] = field(default_factory=list)

    # Full telegram message (generated by reporter)
    telegram_summary:    str = ""

    # Average hold times
    avg_hold_win_min:    float = 0.0
    avg_hold_loss_min:   float = 0.0


# ---------------------------------------------------------------------------
# BacktestReporter
# ---------------------------------------------------------------------------

class BacktestReporter:
    """
    Aggregates backtest results and generates the full performance report.
    """

    def __init__(self) -> None:
        self._db: Optional[aiosqlite.Connection] = None

    # ── lifecycle ──────────────────────────────────────────────────────────

    async def start(self) -> None:
        BACKTEST_DB_PATH.parent.mkdir(parents=True, exist_ok=True)
        self._db = await aiosqlite.connect(str(BACKTEST_DB_PATH))
        self._db.row_factory = aiosqlite.Row
        await self._ensure_tables()

    async def stop(self) -> None:
        if self._db:
            await self._db.close()

    async def _ensure_tables(self) -> None:
        await self._db.execute(
            """
            CREATE TABLE IF NOT EXISTS report_cache (
                id          INTEGER PRIMARY KEY DEFAULT 1,
                report_json TEXT NOT NULL DEFAULT '{}',
                generated_at INTEGER NOT NULL DEFAULT 0
            );
            """
        )
        await self._db.commit()

    # ── helper queries ─────────────────────────────────────────────────────

    async def _best_params_id(self) -> Optional[int]:
        """Return the params_id of the best-performing simulation."""
        async with self._db.execute(
            "SELECT params_id FROM backtest_summary WHERE is_best = 1 ORDER BY id DESC LIMIT 1"
        ) as cur:
            row = await cur.fetchone()
        if row:
            return int(row["params_id"])
        # Fallback: params with highest sharpe
        async with self._db.execute(
            "SELECT params_id FROM backtest_summary ORDER BY sharpe_ratio DESC LIMIT 1"
        ) as cur:
            row = await cur.fetchone()
        return int(row["params_id"]) if row else None

    async def _load_summary_row(self, params_id: int) -> Optional[Dict]:
        async with self._db.execute(
            "SELECT * FROM backtest_summary WHERE params_id = ?", (params_id,)
        ) as cur:
            row = await cur.fetchone()
        return dict(row) if row else None

    async def _load_params_row(self, params_id: int) -> Optional[Dict]:
        async with self._db.execute(
            "SELECT * FROM backtest_params WHERE id = ?", (params_id,)
        ) as cur:
            row = await cur.fetchone()
        return dict(row) if row else None

    async def _total_tokens_analyzed(self) -> int:
        async with self._db.execute(
            "SELECT COUNT(*) FROM historical_tokens WHERE data_complete = 1"
        ) as cur:
            row = await cur.fetchone()
        return int(row[0]) if row else 0

    async def _exit_breakdown(self, params_id: int) -> ExitBreakdown:
        async with self._db.execute(
            """
            SELECT exit_reason, COUNT(*) AS cnt
            FROM backtest_trades
            WHERE params_id = ?
            GROUP BY exit_reason
            """,
            (params_id,),
        ) as cur:
            rows = await cur.fetchall()

        bd = ExitBreakdown()
        for row in rows:
            reason = (row["exit_reason"] or "").lower()
            cnt    = int(row["cnt"])
            if "2x" in reason:
                bd.take_profit_2x  += cnt
            elif "5x" in reason:
                bd.take_profit_5x  += cnt
            elif "10x" in reason:
                bd.take_profit_10x += cnt
            elif "trailing" in reason:
                bd.trailing_stop   += cnt
            elif "emergency" in reason:
                bd.emergency_stop  += cnt
            elif "time" in reason:
                bd.time_stop       += cnt
            else:
                bd.other           += cnt
        return bd

    async def _monthly_breakdown(self, params_id: int) -> List[MonthlyRow]:
        """Load from monthly_performance or compute on-the-fly."""
        async with self._db.execute(
            "SELECT * FROM monthly_performance WHERE params_id = ? ORDER BY year_month",
            (params_id,),
        ) as cur:
            rows = await cur.fetchall()

        if rows:
            return [
                MonthlyRow(
                    year_month=r["year_month"],
                    trades=int(r["trades"]),
                    wins=int(r["wins"]),
                    pnl_sol=float(r["pnl_sol"]),
                    win_rate=float(r["win_rate"]),
                )
                for r in rows
            ]

        # Compute from trades if monthly_performance is empty
        async with self._db.execute(
            """
            SELECT
                strftime('%Y-%m', datetime(ht.created_at, 'unixepoch')) AS ym,
                COUNT(*) AS trades,
                SUM(CASE WHEN bt.pnl_sol > 0 THEN 1 ELSE 0 END) AS wins,
                SUM(bt.pnl_sol) AS pnl_sol
            FROM backtest_trades bt
            JOIN historical_tokens ht ON bt.token_id = ht.id
            WHERE bt.params_id = ?
            GROUP BY ym
            ORDER BY ym
            """,
            (params_id,),
        ) as cur:
            rows = await cur.fetchall()

        result = []
        for r in rows:
            trades = int(r["trades"]) or 1
            wins   = int(r["wins"])
            result.append(MonthlyRow(
                year_month=str(r["ym"] or ""),
                trades=trades,
                wins=wins,
                pnl_sol=float(r["pnl_sol"] or 0),
                win_rate=wins / trades,
            ))
        return result

    async def _score_threshold_analysis(self, params_id: int) -> List[ScoreThresholdRow]:
        """Win rate vs signal score threshold curve."""
        thresholds = [0.60, 0.65, 0.70, 0.72, 0.75, 0.80, 0.85]
        rows = []
        for t in thresholds:
            score_gate = t * 100.0
            async with self._db.execute(
                """
                SELECT
                    COUNT(*) AS trades,
                    SUM(CASE WHEN pnl_sol > 0 THEN 1 ELSE 0 END) AS wins,
                    AVG(pnl_sol) AS avg_pnl,
                    SUM(CASE WHEN pnl_sol > 0 THEN pnl_sol ELSE 0 END) AS gross_profit,
                    SUM(CASE WHEN pnl_sol < 0 THEN ABS(pnl_sol) ELSE 0 END) AS gross_loss
                FROM backtest_trades
                WHERE params_id = ? AND signal_score >= ?
                """,
                (params_id, score_gate),
            ) as cur:
                row = await cur.fetchone()

            if not row or not row["trades"]:
                continue
            trades       = int(row["trades"])
            wins         = int(row["wins"] or 0)
            gross_profit = float(row["gross_profit"] or 0)
            gross_loss   = float(row["gross_loss"]   or 0)
            pf = gross_profit / gross_loss if gross_loss > 0 else float("inf")
            rows.append(ScoreThresholdRow(
                threshold=t,
                trades=trades,
                wins=wins,
                win_rate=wins / trades,
                avg_pnl_sol=float(row["avg_pnl"] or 0),
                profit_factor=min(pf, 99.9),
            ))
        return rows

    async def _rug_analysis(self, params_id: int) -> Tuple[int, float, float]:
        """Returns (rugs_encountered, rugs_caught_pct, avg_rug_loss_pct)."""
        # Total rugs bought (was_rug = 1)
        async with self._db.execute(
            "SELECT COUNT(*) FROM backtest_trades WHERE params_id = ? AND was_rug = 1",
            (params_id,),
        ) as cur:
            row = await cur.fetchone()
        rugs_bought = int(row[0]) if row else 0

        # Total rugs in dataset
        async with self._db.execute(
            "SELECT COUNT(*) FROM historical_tokens WHERE rug_pulled = 1 AND data_complete = 1"
        ) as cur:
            row = await cur.fetchone()
        total_rugs = int(row[0]) if row else 0

        # Rugs caught by gate (in dataset but not bought)
        rugs_caught = max(0, total_rugs - rugs_bought)
        rugs_caught_pct = rugs_caught / total_rugs * 100.0 if total_rugs > 0 else 0.0

        # Average loss on missed rugs (rugs that were bought)
        async with self._db.execute(
            "SELECT AVG(pnl_pct) FROM backtest_trades WHERE params_id = ? AND was_rug = 1",
            (params_id,),
        ) as cur:
            row = await cur.fetchone()
        avg_rug_loss_pct = float(row[0] or 0) * 100.0 if row else 0.0

        return rugs_bought, rugs_caught_pct, avg_rug_loss_pct

    async def _top_feature(self) -> str:
        """Return the highest-importance feature from the RF model."""
        try:
            async with self._db.execute(
                """
                SELECT feature_name, AVG(importance) AS avg_imp
                FROM feature_importance
                WHERE model_name = 'random_forest'
                GROUP BY feature_name
                ORDER BY avg_imp DESC
                LIMIT 1
                """
            ) as cur:
                row = await cur.fetchone()
            return str(row["feature_name"]) if row else "holder_velocity"
        except Exception:
            return "holder_velocity"

    async def _rug_detection_accuracy(self) -> float:
        """Return the ROC-AUC of the rug detection model from ml_accuracy_log."""
        try:
            async with self._db.execute(
                """
                SELECT roc_auc FROM ml_accuracy_log
                WHERE model_name = 'xgb_rug'
                ORDER BY logged_at DESC LIMIT 1
                """
            ) as cur:
                row = await cur.fetchone()
            return float(row["roc_auc"]) if row else 0.0
        except Exception:
            return 0.0

    async def _avg_hold_times(self, params_id: int) -> Tuple[float, float]:
        """Return (avg_hold_win_min, avg_hold_loss_min)."""
        async with self._db.execute(
            """
            SELECT
                AVG(CASE WHEN pnl_sol > 0 THEN hold_time_min END) AS win_hold,
                AVG(CASE WHEN pnl_sol < 0 THEN hold_time_min END) AS loss_hold
            FROM backtest_trades WHERE params_id = ?
            """,
            (params_id,),
        ) as cur:
            row = await cur.fetchone()
        win_h  = float(row["win_hold"]  or 0) if row else 0.0
        loss_h = float(row["loss_hold"] or 0) if row else 0.0
        return win_h, loss_h

    # ── equity curve + Sharpe ──────────────────────────────────────────────

    async def _recompute_equity_curve(self, params_id: int) -> Tuple[List[float], float]:
        """
        Reload per-trade P&L (ordered by token created_at) and recompute
        equity curve + Sharpe ratio.
        """
        async with self._db.execute(
            """
            SELECT bt.pnl_sol
            FROM backtest_trades bt
            JOIN historical_tokens ht ON bt.token_id = ht.id
            WHERE bt.params_id = ?
            ORDER BY ht.created_at ASC
            """,
            (params_id,),
        ) as cur:
            rows = await cur.fetchall()

        pnl_series = [float(r["pnl_sol"]) for r in rows]
        equity = 1.0
        curve  = [equity]
        for pnl in pnl_series:
            equity += pnl
            curve.append(max(equity, 0.0))

        # Sharpe
        if len(pnl_series) >= 2:
            arr  = np.array(pnl_series)
            mean = float(np.mean(arr))
            std  = float(np.std(arr, ddof=1))
            sharpe = (mean / std * math.sqrt(20 * 365)) if std > 0 else 0.0
        else:
            sharpe = 0.0

        return curve, sharpe

    def _max_drawdown(self, equity_curve: List[float]) -> float:
        peak = equity_curve[0] if equity_curve else 1.0
        max_dd = 0.0
        for val in equity_curve:
            if val > peak:
                peak = val
            dd = (peak - val) / peak if peak > 0 else 0.0
            max_dd = max(max_dd, dd)
        return max_dd

    # ── main generate ──────────────────────────────────────────────────────

    async def generate(self, params_id: Optional[int] = None) -> BacktestReport:
        """
        Generate the full report for the best (or specified) param set.
        """
        if params_id is None:
            params_id = await self._best_params_id()
        if params_id is None:
            logger.warning("BacktestReporter: no backtest results found.")
            r = BacktestReport()
            r.telegram_summary = "📭 *No backtest data yet.*\nRun the backtest engine first."
            return r

        summary = await self._load_summary_row(params_id)
        params  = await self._load_params_row(params_id)
        if not summary or not params:
            r = BacktestReport()
            r.telegram_summary = "📭 *No backtest summary found.*"
            return r

        report = BacktestReport()

        # --- Core stats ---
        report.tokens_analyzed  = await self._total_tokens_analyzed()
        report.total_trades     = int(summary.get("total_trades") or 0)
        report.wins             = int(summary.get("wins")         or 0)
        report.losses           = int(summary.get("losses")       or 0)
        report.win_rate         = float(summary.get("win_rate")   or 0)
        report.profit_factor    = float(summary.get("profit_factor") or 0)
        report.total_pnl_sol    = float(summary.get("total_pnl_sol") or 0)
        report.avg_win_pct      = float(summary.get("avg_win_pct")   or 0) * 100.0
        report.avg_loss_pct     = float(summary.get("avg_loss_pct")  or 0) * 100.0
        report.gross_profit_sol = float(summary.get("gross_profit")  or 0)

        # Re-compute equity curve for accurate drawdown
        equity_curve, sharpe = await self._recompute_equity_curve(params_id)
        report.sharpe_ratio      = sharpe
        report.max_drawdown_pct  = self._max_drawdown(equity_curve) * 100.0
        report.starting_sol      = 1.0
        report.ending_sol        = equity_curve[-1] if equity_curve else 1.0
        report.total_pnl_pct     = (report.ending_sol - 1.0) * 100.0

        # Fees estimate (0.002 SOL × 2 × trades)
        report.fees_paid_sol     = report.total_trades * 0.002 * 2

        # Optimal params
        report.optimal_score     = float(params.get("signal_threshold") or 0.72)
        report.optimal_pos_size  = float(params.get("position_size_sol") or 0.05)
        report.optimal_stop_loss = float(params.get("stop_loss_pct")     or 0.30)

        # Rug analysis
        rugs_bought, rugs_caught_pct, avg_rug_loss = await self._rug_analysis(params_id)
        report.rugs_encountered  = rugs_bought
        report.rugs_caught_pct   = rugs_caught_pct
        report.avg_rug_loss_pct  = avg_rug_loss

        # ML
        report.top_feature        = await self._top_feature()
        report.rug_detection_acc  = await self._rug_detection_accuracy() * 100.0

        # Hold times
        report.avg_hold_win_min, report.avg_hold_loss_min = await self._avg_hold_times(params_id)

        # Exit breakdown
        report.exit_breakdown = await self._exit_breakdown(params_id)

        # Monthly breakdown
        report.monthly_rows = await self._monthly_breakdown(params_id)
        if report.monthly_rows:
            best  = max(report.monthly_rows, key=lambda r: r.pnl_sol)
            worst = min(report.monthly_rows, key=lambda r: r.pnl_sol)
            report.best_month      = best.year_month
            report.best_month_pnl  = best.pnl_sol
            report.worst_month     = worst.year_month
            report.worst_month_pnl = worst.pnl_sol

        # Score threshold analysis
        report.score_thresholds = await self._score_threshold_analysis(params_id)

        # Telegram summary
        report.telegram_summary = self._format_telegram(report)

        # Persist to cache
        await self._cache_report(report)

        # Update optimal_parameters.json with any report-level insights
        await self._update_optimal_params(report, params)

        logger.info(
            f"BacktestReporter: report generated. "
            f"Trades={report.total_trades} WR={report.win_rate:.1%} "
            f"PnL={report.total_pnl_pct:+.1f}%"
        )
        return report

    # ── formatters ────────────────────────────────────────────────────────

    def _format_telegram(self, r: BacktestReport) -> str:
        pnl_emoji = "🟢" if r.total_pnl_sol >= 0 else "🔴"
        return (
            f"📊 *BACKTEST REPORT*\n"
            f"━━━━━━━━━━━━━━━━━━\n"
            f"Tokens Analyzed: `{r.tokens_analyzed:,}`\n"
            f"Trades Simulated: `{r.total_trades:,}`\n"
            f"━━━━━━━━━━━━━━━━━━\n"
            f"✅ Win Rate: `{r.win_rate:.1%}`\n"
            f"💰 Avg Win: `+{r.avg_win_pct:.0f}%`\n"
            f"📉 Avg Loss: `-{abs(r.avg_loss_pct):.0f}%`\n"
            f"📈 Profit Factor: `{r.profit_factor:.2f}`\n"
            f"🔻 Max Drawdown: `-{r.max_drawdown_pct:.1f}%`\n"
            f"📐 Sharpe Ratio: `{r.sharpe_ratio:.3f}`\n"
            f"━━━━━━━━━━━━━━━━━━\n"
            f"🎯 Optimal Score: `{r.optimal_score:.2f}`\n"
            f"💡 Best Feature: `{r.top_feature}`\n"
            f"🔴 Rug Detection: `{r.rug_detection_acc:.1f}% accuracy`\n"
            f"━━━━━━━━━━━━━━━━━━\n"
            f"Starting: `1.00 SOL`\n"
            f"{pnl_emoji} Ending:   `{r.ending_sol:.4f} SOL` "
            f"(`{r.total_pnl_pct:+.1f}%`)"
        )

    def _format_exit_breakdown(self, r: BacktestReport) -> str:
        bd = r.exit_breakdown
        total = max(bd.total, 1)
        return (
            f"🚪 *Exit Breakdown* ({total} trades)\n"
            f"├── 2x TP:       `{bd.take_profit_2x:,}` ({bd.take_profit_2x/total:.0%})\n"
            f"├── 5x TP:       `{bd.take_profit_5x:,}` ({bd.take_profit_5x/total:.0%})\n"
            f"├── 10x TP:      `{bd.take_profit_10x:,}` ({bd.take_profit_10x/total:.0%})\n"
            f"├── Trailing:    `{bd.trailing_stop:,}` ({bd.trailing_stop/total:.0%})\n"
            f"├── Emergency:   `{bd.emergency_stop:,}` ({bd.emergency_stop/total:.0%})\n"
            f"└── Time stop:   `{bd.time_stop:,}` ({bd.time_stop/total:.0%})"
        )

    def _format_monthly(self, r: BacktestReport) -> str:
        if not r.monthly_rows:
            return "📅 *Monthly breakdown: no data yet.*"
        lines = ["📅 *Monthly Performance*\n"]
        for row in r.monthly_rows[-6:]:   # last 6 months
            emoji = "🟢" if row.pnl_sol >= 0 else "🔴"
            lines.append(
                f"{emoji} `{row.year_month}` — "
                f"WR: `{row.win_rate:.0%}` | "
                f"P&L: `{row.pnl_sol:+.4f} SOL`"
            )
        if r.best_month:
            lines.append(f"\n🏆 Best: `{r.best_month}` (`{r.best_month_pnl:+.4f} SOL`)")
        if r.worst_month:
            lines.append(f"💀 Worst: `{r.worst_month}` (`{r.worst_month_pnl:+.4f} SOL`)")
        return "\n".join(lines)

    def _format_score_analysis(self, r: BacktestReport) -> str:
        if not r.score_thresholds:
            return "📊 *Score analysis: no data.*"
        lines = ["📊 *Signal Score Threshold Analysis*\n"]
        for row in r.score_thresholds:
            indicator = " ← optimal" if abs(row.threshold - r.optimal_score) < 0.01 else ""
            lines.append(
                f"`{row.threshold:.2f}` → "
                f"WR: `{row.win_rate:.0%}` | "
                f"PF: `{row.profit_factor:.2f}` | "
                f"Trades: `{row.trades:,}`"
                f"{indicator}"
            )
        return "\n".join(lines)

    def _format_full_report(self, r: BacktestReport) -> str:
        """Full multi-section report for /backtest_report command."""
        sections = [
            r.telegram_summary,
            "",
            self._format_exit_breakdown(r),
            "",
            self._format_monthly(r),
            "",
            self._format_score_analysis(r),
            "",
            f"⏱️ *Hold Times*\n"
            f"Winners avg: `{r.avg_hold_win_min:.0f} min`\n"
            f"Losers avg:  `{r.avg_hold_loss_min:.0f} min`",
            "",
            f"🛡️ *Rug Analysis*\n"
            f"Rugs bought: `{r.rugs_encountered}`\n"
            f"Rugs caught by gate: `{r.rugs_caught_pct:.1f}%`\n"
            f"Avg loss on rug: `{r.avg_rug_loss_pct:.1f}%`",
        ]
        return "\n".join(sections)

    def format_status_message(self) -> str:
        """Minimal status for /backtest_status before report is generated."""
        if OPT_PARAMS_PATH.exists():
            try:
                data = json.loads(OPT_PARAMS_PATH.read_text())
                summ = data.get("backtest_summary", {})
                return (
                    f"✅ *Backtest complete*\n"
                    f"Trades: `{summ.get('total_trades', 0):,}`\n"
                    f"Win rate: `{summ.get('win_rate', 0):.1%}`\n"
                    f"Sharpe: `{summ.get('sharpe_ratio', 0):.3f}`\n"
                    f"Use /backtest_report for full details."
                )
            except Exception:
                pass
        return "⏳ *Backtest not yet run.* Use `/optimize` to start."

    # ── cache + export ─────────────────────────────────────────────────────

    async def _cache_report(self, report: BacktestReport) -> None:
        """Cache the report JSON for quick retrieval."""
        try:
            payload = {
                "telegram_summary": report.telegram_summary,
                "total_trades": report.total_trades,
                "win_rate": report.win_rate,
                "sharpe_ratio": report.sharpe_ratio,
                "max_drawdown_pct": report.max_drawdown_pct,
                "total_pnl_sol": report.total_pnl_sol,
                "total_pnl_pct": report.total_pnl_pct,
                "ending_sol": report.ending_sol,
                "generated_at": int(time.time()),
            }
            await self._db.execute(
                "INSERT OR REPLACE INTO report_cache (id, report_json, generated_at) VALUES (1, ?, ?)",
                (json.dumps(payload), int(time.time())),
            )
            await self._db.commit()
        except Exception as exc:
            logger.error(f"BacktestReporter: cache write failed: {exc}")

    async def get_cached_summary(self) -> Optional[str]:
        """Return cached telegram_summary if available."""
        try:
            async with self._db.execute(
                "SELECT report_json FROM report_cache WHERE id = 1"
            ) as cur:
                row = await cur.fetchone()
            if row:
                data = json.loads(row["report_json"])
                return data.get("telegram_summary")
        except Exception:
            pass
        return None

    async def _update_optimal_params(
        self, report: BacktestReport, params: Dict
    ) -> None:
        """Merge report insights into optimal_parameters.json."""
        try:
            existing: Dict = {}
            if OPT_PARAMS_PATH.exists():
                existing = json.loads(OPT_PARAMS_PATH.read_text())

            existing.update({
                "generated_at": int(time.time()),
                "backtest_summary": {
                    "total_trades": report.total_trades,
                    "win_rate": round(report.win_rate, 4),
                    "sharpe_ratio": round(report.sharpe_ratio, 4),
                    "profit_factor": round(report.profit_factor, 4),
                    "max_drawdown_pct": round(report.max_drawdown_pct, 4),
                    "total_pnl_sol": round(report.total_pnl_sol, 6),
                    "total_pnl_pct": round(report.total_pnl_pct, 2),
                },
                "min_signal_score": report.optimal_score,
                "position_size_sol": report.optimal_pos_size,
                "stop_loss_pct": report.optimal_stop_loss,
                "top_feature": report.top_feature,
                "rug_detection_accuracy": round(report.rug_detection_acc, 2),
            })
            OPT_PARAMS_PATH.write_text(json.dumps(existing, indent=2))
            logger.info(f"BacktestReporter: updated {OPT_PARAMS_PATH}")
        except Exception as exc:
            logger.error(f"BacktestReporter: optimal params update failed: {exc}")

    # ── auto-apply to signal_engine ────────────────────────────────────────

    @staticmethod
    def apply_optimal_params_to_settings() -> bool:
        """
        Read optimal_parameters.json and update live settings at runtime.
        Returns True if params were applied.
        """
        if not OPT_PARAMS_PATH.exists():
            return False
        try:
            data = json.loads(OPT_PARAMS_PATH.read_text())
            from config.settings import runtime_state
            min_score = float(data.get("min_signal_score", 0.72))
            runtime_state.min_signal_score_for_buy = min_score * 100.0 if min_score <= 1.0 else min_score
            pos_size = float(data.get("position_size_sol", 0.05))
            runtime_state.max_position_size_sol = pos_size
            logger.info(
                f"BacktestReporter: applied optimal params — "
                f"score_threshold={min_score} pos_size={pos_size} SOL"
            )
            return True
        except Exception as exc:
            logger.error(f"BacktestReporter: failed to apply optimal params: {exc}")
            return False

    # ── convenience ────────────────────────────────────────────────────────

    async def run(self) -> BacktestReport:
        """Convenience: start → generate → stop."""
        await self.start()
        try:
            return await self.generate()
        finally:
            await self.stop()

    async def get_full_report_message(self) -> str:
        """Return the full formatted report for /backtest_report Telegram command."""
        await self.start()
        try:
            report = await self.generate()
            return self._format_full_report(report)
        finally:
            await self.stop()

    @staticmethod
    def format_status_message_static() -> str:
        """Class-level status check callable without instantiation."""
        if OPT_PARAMS_PATH.exists():
            try:
                data = json.loads(OPT_PARAMS_PATH.read_text())
                summ = data.get("backtest_summary", {})
                return (
                    f"✅ *Backtest complete*\n"
                    f"Trades: `{summ.get('total_trades', 0):,}`\n"
                    f"Win rate: `{summ.get('win_rate', 0):.1%}`\n"
                    f"Sharpe: `{summ.get('sharpe_ratio', 0):.3f}`\n"
                    f"P&L: `{summ.get('total_pnl_pct', 0):+.1f}%`\n"
                    f"Use /backtest_report for full details."
                )
            except Exception:
                pass
        return "⏳ *Backtest not yet run.* Use `/optimize` to start."

    # Async context manager for convenient one-shot use
    async def __aenter__(self) -> "BacktestReporter":
        await self.start()
        return self

    async def __aexit__(self, *_) -> None:
        await self.stop()


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------

backtest_reporter = BacktestReporter()


# ---------------------------------------------------------------------------
# __main__
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import asyncio
    import argparse

    parser = argparse.ArgumentParser(description="Generate backtest performance report")
    parser.add_argument("--params-id", type=int, default=0, help="Specific params_id to report on")
    args = parser.parse_args()

    async def main() -> None:
        reporter = BacktestReporter()
        await reporter.start()
        try:
            report = await reporter.generate(
                params_id=args.params_id if args.params_id > 0 else None
            )
            print("\n" + "=" * 60)
            print(report.telegram_summary.replace("*", "").replace("`", ""))
            print("=" * 60)
            print(reporter._format_exit_breakdown(report).replace("`", ""))
            print()
            print(reporter._format_monthly(report).replace("`", ""))
            print()
            print(reporter._format_score_analysis(report).replace("`", ""))
            print()
            applied = BacktestReporter.apply_optimal_params_to_settings()
            if applied:
                print("✅ Optimal parameters applied to live settings.")
        finally:
            await reporter.stop()

    asyncio.run(main())
