# core/signal_engine.py
"""
Signal evaluation and Telegram message formatting.

Phase 2 score formula (weights sum to 1.00):
    SIGNAL_SCORE =
        security_score          × 0.20
      + wallet_score            × 0.15
      + rug_score               × 0.15
      + holder_velocity_score   × 0.15
      + smart_money_score       × 0.15
      + tx_pattern_score        × 0.10
      + social_score            × 0.05
      + cross_dex_score         × 0.05

(liquidity_growth_score acts as a gate / tie-breaker rather than a
direct weight component, to avoid over-weighting candle data for
tokens that are <2 minutes old when analysed.)

Gate evaluation order
---------------------
① Social confidence boost (+10 pts when social_score > 60) — BEFORE gates.
② Security score gate           (< 70 → fail)
③ Confidence gate               (< 65 → fail, uses boosted value)
④ Liquidity gate                (< $10k → fail)
⑤ Volume spike gate             (< 2× → fail)
⑥ Wallet CRITICAL gate          → fail
⑦ Rug RUG verdict gate          → fail
⑧ Holder-velocity rug warning   → fail
⑨ Cross-DEX manipulation gate   → fail (gap ≥ 10%)
⑩ Liquidity spike gate          (ARTIFICIAL_SPIKE pattern → warn / reduce score)
⑪ TX pattern gate               (is_artificial_pump → warn / reduce score)
⑫ Composite score gate          (< 50/100 → fail)
"""

from typing import Any, Optional
from loguru import logger
from security.scanner import SecurityResult
from core.token_analyzer import AnalysisResult
from core.solana_scanner import TokenInfo
from config.settings import settings as _settings, runtime_state

# ---------------------------------------------------------------------------
# Phase 2 scoring weights (must sum to 1.00)
# These are updated at startup by load_weights_from_optimal_params()
# ---------------------------------------------------------------------------
_W_SECURITY:         float = 0.20
_W_WALLET:           float = 0.15
_W_RUG:              float = 0.15
_W_HOLDER_VELOCITY:  float = 0.15
_W_SMART_MONEY:      float = 0.15
_W_TX_PATTERN:       float = 0.10
_W_SOCIAL:           float = 0.05
_W_CROSS_DEX:        float = 0.05

# Minimum composite score to emit a signal (0–100)
_MIN_COMPOSITE_SCORE: float = 50.0

# ---------------------------------------------------------------------------
# Public weight accessors (used by backtest_engine to stay in sync)
# ---------------------------------------------------------------------------

def get_signal_weights() -> dict[str, float]:
    return {
        "security":        _W_SECURITY,
        "wallet":          _W_WALLET,
        "rug":             _W_RUG,
        "holder_velocity": _W_HOLDER_VELOCITY,
        "smart_money":     _W_SMART_MONEY,
        "tx_pattern":      _W_TX_PATTERN,
        "social":          _W_SOCIAL,
        "cross_dex":       _W_CROSS_DEX,
    }

def get_min_composite_score() -> float:
    return _MIN_COMPOSITE_SCORE

# ---------------------------------------------------------------------------
# Backtest / ML integration
# ---------------------------------------------------------------------------

def load_weights_from_optimal_params() -> bool:
    """
    Load signal weights and threshold from models/optimal_parameters.json
    generated by the backtest engine.  Idempotent — safe to call on startup.
    Returns True if weights were updated.
    """
    import json
    from pathlib import Path
    global _W_SECURITY, _W_WALLET, _W_RUG, _W_HOLDER_VELOCITY
    global _W_SMART_MONEY, _W_TX_PATTERN, _W_SOCIAL, _W_CROSS_DEX
    global _MIN_COMPOSITE_SCORE

    path = Path(__file__).parent.parent / "models" / "optimal_parameters.json"
    if not path.exists():
        return False
    try:
        data   = json.loads(path.read_text())
        weights = data.get("signal_weights", {})
        if weights:
            _W_SECURITY        = float(weights.get("security",        _W_SECURITY))
            _W_WALLET          = float(weights.get("wallet",          _W_WALLET))
            _W_RUG             = float(weights.get("rug",             _W_RUG))
            _W_HOLDER_VELOCITY = float(weights.get("holder_velocity", _W_HOLDER_VELOCITY))
            _W_SMART_MONEY     = float(weights.get("smart_money",     _W_SMART_MONEY))
            _W_TX_PATTERN      = float(weights.get("tx_pattern",      _W_TX_PATTERN))
            _W_SOCIAL          = float(weights.get("social",          _W_SOCIAL))
            _W_CROSS_DEX       = float(weights.get("cross_dex",       _W_CROSS_DEX))
        min_score = data.get("min_signal_score")
        if min_score is not None:
            _MIN_COMPOSITE_SCORE = float(min_score) * 100.0 \
                if float(min_score) <= 1.0 else float(min_score)
        logger.info(
            "signal_engine: loaded weights from optimal_parameters.json — "
            f"threshold={_MIN_COMPOSITE_SCORE:.0f}/100"
        )
        return True
    except Exception as exc:
        logger.warning(f"signal_engine: could not load optimal params: {exc}")
        return False


# Attempt to load optimised weights at import time (no-op if file absent)
load_weights_from_optimal_params()


# ---------------------------------------------------------------------------
# Lazy ML model access
# ---------------------------------------------------------------------------

def _get_ml_prediction(
    token_info: Any,
    analysis_result: Any,
    security_result: Any,
    wallet_analysis: Any,
) -> Optional[Any]:
    """
    Attempt to get ML probability predictions.  Returns an MLPrediction
    or None if models aren't loaded / libraries missing.
    """
    try:
        from backtesting.ml_optimizer import MLOptimizer
        opt = MLOptimizer()
        if not opt.load_models():
            return None
        return opt.predict(token_info, analysis_result, security_result, wallet_analysis)
    except Exception:
        return None  # silently degrade if backtesting module missing



class SignalDecision:
    def __init__(
        self,
        send: bool,
        reason: str = "",
        composite_score: float = 0.0,
        buy_recommended: bool = False,
        recommended_position_sol: float = 0.0,
        ml_pred: Optional[Any] = None,
    ) -> None:
        self.send                    = send
        self.reason                  = reason
        self.composite_score         = composite_score   # 0–100 weighted aggregate
        self.buy_recommended         = buy_recommended   # True when score ≥ MIN_SIGNAL_SCORE_FOR_BUY
        self.recommended_position_sol = recommended_position_sol  # fractional Kelly hint
        self.ml_pred                 = ml_pred


# ---------------------------------------------------------------------------
# Gate evaluation
# ---------------------------------------------------------------------------

def evaluate_signal(
    token_info:       TokenInfo,
    security_res:     SecurityResult,
    analysis_res:     AnalysisResult,
    wallet_analysis:  Optional[Any] = None,   # WalletAnalysis
    rug_analysis:     Optional[Any] = None,   # RugAnalysis
    social_signals:   Optional[Any] = None,   # SocialSignals
    holder_velocity:  Optional[Any] = None,   # HolderVelocityResult  (Phase 1)
    smart_money:      Optional[Any] = None,   # FirstBuyerAnalysis    (Phase 1)
    tx_pattern:       Optional[Any] = None,   # TxPatternResult       (Phase 2)
    liquidity_growth: Optional[Any] = None,   # LiquidityGrowthResult (Phase 2)
    cross_dex:        Optional[Any] = None,   # CrossDexResult        (Phase 2)
) -> SignalDecision:
    """
    Evaluate whether a token deserves a signal alert.

    Always returns a SignalDecision — never raises.
    """
    fail_reasons: list[str] = []
    boosted_confidence = analysis_res.confidence_score

    # ── ① Social confidence boost ─────────────────────────────────────
    if social_signals and social_signals.social_score > 60.0:
        boosted_confidence = min(100.0, analysis_res.confidence_score + 10.0)
        logger.info(
            f"Social boost for {token_info.address}: "
            f"confidence {analysis_res.confidence_score:.1f} → {boosted_confidence:.1f}"
        )

    # ── ②–⑤ Core gates ────────────────────────────────────────────────
    if security_res.score < 70.0:
        fail_reasons.append(
            f"Security score too low ({security_res.score:.1f}/100)"
        )
    if boosted_confidence < 65.0:
        fail_reasons.append(
            f"Confidence too low ({analysis_res.confidence_score:.1f}/100)"
        )
    if token_info.liquidity_usd < 10_000.0:
        fail_reasons.append(
            f"Liquidity too low (${token_info.liquidity_usd:,.2f})"
        )
    if analysis_res.volume_spike_ratio < 2.0:
        fail_reasons.append(
            f"Volume spike too weak ({analysis_res.volume_spike_ratio:.2f}×)"
        )

    # ── ⑥ Wallet CRITICAL gate ────────────────────────────────────────
    if wallet_analysis and wallet_analysis.risk_level == "CRITICAL":
        fail_reasons.append(
            f"Creator wallet CRITICAL risk "
            f"(score={wallet_analysis.wallet_score:.0f}/100, "
            f"age={wallet_analysis.wallet_age_days}d)"
        )

    # ── ⑦ Rug verdict gate ────────────────────────────────────────────
    if rug_analysis and rug_analysis.recommendation == "RUG":
        fail_reasons.append(
            f"Rug pull pattern detected ({rug_analysis.rug_probability:.0%})"
        )

    # ── ⑧ Holder-velocity rug warning ────────────────────────────────
    if holder_velocity and holder_velocity.is_rug_warning:
        fail_reasons.append(
            f"Holder-drop rug warning "
            f"({holder_velocity.current_holders} holders, "
            f"peak was {holder_velocity.peak_holders})"
        )

    # ── ⑨ Cross-DEX manipulation gate ────────────────────────────────
    if cross_dex and cross_dex.is_manipulated:
        fail_reasons.append(
            f"Cross-DEX price manipulation detected "
            f"(gap={cross_dex.price_gap_pct:.1f}% across {cross_dex.source_count} sources)"
        )

    # ── ⑩–⑪ Soft gates (reduce score, add warning, don't hard-fail) ──
    # These are already baked into the module scores; logged here for audit.
    if liquidity_growth and liquidity_growth.growth_pattern == "ARTIFICIAL_SPIKE":
        logger.warning(
            f"Artificial liquidity spike pattern for {token_info.address} "
            f"(first-candle vol = {liquidity_growth.first_candle_vol_pct:.0%})"
        )
    if tx_pattern and tx_pattern.is_artificial_pump:
        logger.warning(
            f"Artificial pump tx pattern for {token_info.address} "
            f"(buy_ratio={tx_pattern.buy_ratio:.0%}, wash={tx_pattern.wash_trade_count})"
        )

    # ── ⑫ ML prediction (Part 4) ─────────────────────────────────────
    ml_pred: Optional[Any] = None
    try:
        from backtesting.ml_optimizer import MLOptimizer
        _ml_opt = MLOptimizer()
        if _ml_opt.load_models():
            ml_pred = _ml_opt.predict(token_info, analysis_res, security_res, wallet_analysis)
    except Exception:
        pass

    ml_gates_active = ml_pred is not None and hasattr(ml_pred, 'should_signal')

    if ml_gates_active:
        # Replace confidence gate with ML pump probability
        if ml_pred.pump_probability < 0.55:
            fail_reasons.append(
                f"ML pump probability too low ({ml_pred.pump_probability:.0%})"
            )
        # Replace rug gate with ML rug probability
        if ml_pred.rug_probability > 0.35:
            fail_reasons.append(
                f"ML rug probability too high ({ml_pred.rug_probability:.0%})"
            )
    else:
        # ── ⑫–⑬ ML not available — use rule-based gates ──────────────
        # Rug gate already handled above at ⑦
        pass

    # ── ⑭ Composite SIGNAL_SCORE ─────────────────────────────────────
    NEUTRAL = 50.0
    sec_score  = security_res.score
    wal_score  = wallet_analysis.wallet_score           if wallet_analysis  else NEUTRAL
    rug_score  = rug_analysis.pattern_score             if rug_analysis     else NEUTRAL
    hv_score   = holder_velocity.holder_velocity_score  if holder_velocity  else NEUTRAL
    sm_score   = smart_money.smart_money_score          if smart_money      else NEUTRAL
    txp_score  = tx_pattern.tx_pattern_score            if tx_pattern       else NEUTRAL
    soc_score  = social_signals.social_score            if social_signals   else NEUTRAL
    cdx_score  = cross_dex.cross_dex_score              if cross_dex        else NEUTRAL

    composite = (
        sec_score * _W_SECURITY
        + wal_score  * _W_WALLET
        + rug_score  * _W_RUG
        + hv_score   * _W_HOLDER_VELOCITY
        + sm_score   * _W_SMART_MONEY
        + txp_score  * _W_TX_PATTERN
        + soc_score  * _W_SOCIAL
        + cdx_score  * _W_CROSS_DEX
    )

    if ml_gates_active:
        ml_score_weight = 0.10
        weighted_ml = ml_pred.ml_score * ml_score_weight
        remaining = 1.0 - ml_score_weight
        composite = composite * remaining + weighted_ml

    composite = round(composite, 2)

    logger.info(
        f"SIGNAL_SCORE for {token_info.address}: {composite:.1f}/100 "
        f"[sec={sec_score:.0f} wal={wal_score:.0f} rug={rug_score:.0f} "
        f"hv={hv_score:.0f} sm={sm_score:.0f} txp={txp_score:.0f} "
        f"soc={soc_score:.0f} cdx={cdx_score:.0f}]"
        + (f" ml={ml_pred.ml_score:.0f}" if ml_gates_active else "")
    )

    if composite < _MIN_COMPOSITE_SCORE and not fail_reasons:
        fail_reasons.append(
            f"Composite signal score too low ({composite:.1f}/100 < {_MIN_COMPOSITE_SCORE})"
        )

    send   = len(fail_reasons) == 0
    reason = "All checks passed!" if send else "; ".join(fail_reasons)

    # --- Auto-buy recommendation ---
    min_score_threshold = runtime_state.min_signal_score_for_buy
    buy_recommended = send and (composite >= min_score_threshold)

    return SignalDecision(
        send=send,
        reason=reason,
        composite_score=composite,
        ml_pred=ml_pred,
        buy_recommended=buy_recommended,
    )


# ---------------------------------------------------------------------------
# Private emoji helpers
# ---------------------------------------------------------------------------

def _risk_emoji(level: str) -> str:
    return {"LOW": "🟢", "MEDIUM": "🟡", "HIGH": "🟠", "CRITICAL": "🔴"}.get(level, "⚪")

def _rug_emoji(rec: str) -> str:
    return {"SAFE": "✅", "CAUTION": "⚠️", "AVOID": "🚫", "RUG": "💀"}.get(rec, "❓")

def _velocity_emoji(label: str) -> str:
    return {
        "STRONG":   "🚀",
        "MODERATE": "📈",
        "SLOW":     "🐌",
        "STAGNANT": "😐",
        "DROPPING": "🩸",
    }.get(label, "❓")

def _growth_emoji(pattern: str) -> str:
    return {
        "ORGANIC":           "🌱",
        "CONSISTENT":        "📊",
        "FLATLINE":          "➡️",
        "DECLINING":         "📉",
        "ARTIFICIAL_SPIKE":  "🚨",
        "INSUFFICIENT_DATA": "❓",
    }.get(pattern, "❓")

def _gap_emoji(label: str) -> str:
    return {
        "HEALTHY":      "✅",
        "ACCEPTABLE":   "🟡",
        "SUSPICIOUS":   "🟠",
        "MANIPULATED":  "🔴",
        "UNKNOWN":      "⚪",
    }.get(label, "⚪")


# ---------------------------------------------------------------------------
# Message formatter
# ---------------------------------------------------------------------------

def format_signal_message(
    token_info:       TokenInfo,
    security_res:     SecurityResult,
    analysis_res:     AnalysisResult,
    wallet_analysis:  Optional[Any] = None,
    rug_analysis:     Optional[Any] = None,
    social_signals:   Optional[Any] = None,
    holder_velocity:  Optional[Any] = None,
    smart_money:      Optional[Any] = None,
    tx_pattern:       Optional[Any] = None,
    liquidity_growth: Optional[Any] = None,
    cross_dex:        Optional[Any] = None,
    composite_score:  float = 0.0,
    ml_pred:          Optional[Any] = None,
) -> str:
    """Build the full Telegram-formatted signal message."""
    mint        = token_info.address
    dex_source  = token_info.dex_source if hasattr(token_info, "dex_source") else "Raydium_AMM"
    latency_ms  = token_info.detection_latency_ms if hasattr(token_info, "detection_latency_ms") else 0.0
    dex_link    = f"https://dexscreener.com/solana/{mint}"

    # ── Header ────────────────────────────────────────────────────────
    msg = (
        f"🚀 **NEW SOLANA SIGNAL DETECTED** 🚀\n\n"
        f"💎 **Token:** {token_info.name} ({token_info.symbol})\n"
        f"📍 **Mint:** `{mint}`\n"
        f"🏦 **DEX:** `{dex_source}`"
        + (f" ⚡ `{latency_ms:.0f}ms`" if latency_ms > 0 else "") + "\n"
        f"💵 **Price:** ${token_info.price:,.6f}\n"
        f"💦 **Liquidity:** ${token_info.liquidity_usd:,.2f}\n"
        f"📊 **Market Cap:** ${token_info.market_cap:,.2f}\n"
        f"🎯 **Signal Score:** `{composite_score:.1f}/100`\n"
    )

    # ── ML Prediction data ────────────────────────────────────────────
    if ml_pred and hasattr(ml_pred, 'ml_score'):
        msg += (
            f"🤖 **ML Score:** `{ml_pred.ml_score:.0f}/100`\n"
            f"⏱ **Best Entry:** `T+{ml_pred.entry_minutes}min`\n"
            f"📈 **Pump Prob:** `{ml_pred.pump_probability:.0%}` | "
            f"🛑 **Rug Prob:** `{ml_pred.rug_probability:.0%}`\n"
        )
    msg += "\n"

    # ── Security ──────────────────────────────────────────────────────
    msg += (
        f"🛡️ **Security Scan:**\n"
        f"  - Score: `{security_res.score:.1f}/100`\n"
        f"  - Status: {'✅ Passed' if security_res.passed else '❌ Failed'}\n"
        f"  - Scan Status: `{security_res.scan_status}`\n"
        f"  - Fail Reason: {security_res.fail_reason or 'None'}\n\n"
    )

    # ── Technical Analysis ────────────────────────────────────────────
    msg += (
        f"📈 **Technical Analysis:**\n"
        f"  - Confidence: `{analysis_res.confidence_score:.1f}/100`\n"
        f"  - RSI (1m): `{analysis_res.rsi:.1f}`\n"
        f"  - Volume Spike: `{analysis_res.volume_spike_ratio:.2f}×`\n"
        f"  - Price Momentum: `{analysis_res.momentum_score:.1f}/100`\n"
    )

    # ── Wallet Analysis ───────────────────────────────────────────────
    if wallet_analysis:
        risk_icon  = _risk_emoji(wallet_analysis.risk_level)
        new_tag    = "  🆕 NEW WALLET" if wallet_analysis.is_new_wallet else ""
        sniper_tag = (
            f" ⚠️ {wallet_analysis.sniper_percentage:.0f}% sniped"
            if wallet_analysis.sniper_percentage > 10.0 else ""
        )
        msg += (
            f"\n👛 **Wallet Analysis:**\n"
            f"  - Creator Age: `{wallet_analysis.wallet_age_days}d`{new_tag}\n"
            f"  - Snipers: `{wallet_analysis.sniper_count}`{sniper_tag}\n"
            f"  - Wallet Score: `{wallet_analysis.wallet_score:.0f}/100`\n"
            f"  - Risk Level: {risk_icon} `{wallet_analysis.risk_level}`\n"
        )

    # ── Rug Detection ─────────────────────────────────────────────────
    if rug_analysis:
        rug_icon  = _rug_emoji(rug_analysis.recommendation)
        flags_str = (
            "\n".join(f"    ⚑ {f}" for f in rug_analysis.risk_flags)
            if rug_analysis.risk_flags else "    None detected"
        )
        msg += (
            f"\n🔍 **Rug Detection:**\n"
            f"  - Rug Probability: `{rug_analysis.rug_probability:.0%}`\n"
            f"  - Pattern Score: `{rug_analysis.pattern_score:.0f}/100`\n"
            f"  - Verdict: {rug_icon} `{rug_analysis.recommendation}`\n"
            f"  - Flags:\n{flags_str}\n"
        )

    # ── Holder Velocity (Phase 1) ─────────────────────────────────────
    if holder_velocity:
        vel_icon  = _velocity_emoji(holder_velocity.velocity_label)
        rug_warn  = "  🩸 RUG WARNING" if holder_velocity.is_rug_warning else ""
        msg += (
            f"\n👥 **Holder Velocity:**\n"
            f"  - Holders: `{holder_velocity.current_holders:,}`{rug_warn}\n"
            f"  - Growth: `{holder_velocity.holders_per_minute:.1f}/min` "
            f"{vel_icon} `{holder_velocity.velocity_label}`\n"
            f"  - Velocity Score: `{holder_velocity.holder_velocity_score:.0f}/100`\n"
        )

    # ── Smart Money (Phase 1) ─────────────────────────────────────────
    if smart_money and smart_money.analyzed_wallets > 0:
        sm_icon = "🧠" if smart_money.smart_money_count > 0 else "👤"
        msg += (
            f"\n{sm_icon} **Smart Money:**\n"
            f"  - First Buyers: `{len(smart_money.first_buyers)}`\n"
            f"  - Smart Money: `{smart_money.smart_money_count}` "
            f"({smart_money.smart_money_pct:.0f}%)\n"
            f"  - SM Score: `{smart_money.smart_money_score:.0f}/100`\n"
        )

    # ── TX Pattern (Phase 2) ──────────────────────────────────────────
    if tx_pattern and tx_pattern.total_txs > 0:
        pump_tag = "  🚨 PUMP" if tx_pattern.is_artificial_pump else ""
        wash_tag = (
            f"  ⚠️ {tx_pattern.wash_trade_count} wash trades"
            if tx_pattern.wash_trade_count > 0 else ""
        )
        msg += (
            f"\n📊 **TX Pattern:**\n"
            f"  - Txs: `{tx_pattern.total_txs}` "
            f"({tx_pattern.buy_count} buy / {tx_pattern.sell_count} sell){pump_tag}\n"
            f"  - Buy Ratio: `{tx_pattern.buy_ratio:.0%}`{wash_tag}\n"
            f"  - Pattern Score: `{tx_pattern.tx_pattern_score:.0f}/100`\n"
        )

    # ── Liquidity Growth (Phase 2) ────────────────────────────────────
    if liquidity_growth and liquidity_growth.candle_count > 0:
        grow_icon = _growth_emoji(liquidity_growth.growth_pattern)
        msg += (
            f"\n💧 **Liquidity Growth:**\n"
            f"  - Pattern: {grow_icon} `{liquidity_growth.growth_pattern}`\n"
            f"  - Candles: `{liquidity_growth.candle_count}` × 1m "
            f"| Vol CV: `{liquidity_growth.volume_cv:.2f}`\n"
            f"  - Price Change: `{liquidity_growth.growth_rate_pct:+.2f}%`\n"
            f"  - Growth Score: `{liquidity_growth.liquidity_growth_score:.0f}/100`\n"
        )

    # ── Cross-DEX (Phase 2) ───────────────────────────────────────────
    if cross_dex and cross_dex.source_count >= 2:
        gap_icon = _gap_emoji(cross_dex.gap_label)
        prices_str = " / ".join(
            f"{src}: ${p:.8f}" for src, p in cross_dex.prices.items()
        )
        msg += (
            f"\n🔀 **Cross-DEX:**\n"
            f"  - Sources: `{cross_dex.source_count}` ({prices_str})\n"
            f"  - Price Gap: `{cross_dex.price_gap_pct:.2f}%` "
            f"{gap_icon} `{cross_dex.gap_label}`\n"
            f"  - Cross-DEX Score: `{cross_dex.cross_dex_score:.0f}/100`\n"
        )

    # ── Social Signals ────────────────────────────────────────────────
    if social_signals:
        viral_tag = " 🔥 VIRAL"       if social_signals.has_viral_tweet     else ""
        inf_tag   = " 🌟 Influencer"  if social_signals.influencer_mentioned else ""
        msg += (
            f"\n📣 **Social Signals:**\n"
            f"  - Mentions (1h): `{social_signals.mention_count_1h}`{viral_tag}{inf_tag}\n"
            f"  - Velocity: `{social_signals.mention_velocity:.2f}/min`\n"
            f"  - Sentiment: `{social_signals.sentiment_score:.0f}/100`\n"
            f"  - Social Score: `{social_signals.social_score:.0f}/100`\n"
        )

    msg += f"\n🔗 [DexScreener]({dex_link})"
    return msg
